In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import TimeSeriesSplit, GridSearchCV
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.metrics import mean_squared_error, r2_score

# Models
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, ExtraTreesRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

In [2]:
data = pd.read_csv(r"C:\Users\manju\OneDrive\Desktop\Documents\Data Analytics\DA Semester 4\Capstone 2\ML Modelling\ml_dataset.csv")
data.head().T

,0,1,2,3,4
year,2012,2012,2012,2012,2012
state_code,NY,IN,SC,IN,AL
provider_type,General Short-Term (includes CAH),General Short-Term (includes CAH),Psychiatric Hospital,Psychiatric Hospital,General Short-Term (includes CAH)
ccn_facility_type,Short-Term Hospital,Short-Term Hospital,Psychiatric Hospital,Psychiatric Hospital,Short-Term Hospital
number_of_beds,66.0,66.0,66.0,66.0,25.0
total_bed_days_available,23424.0,23424.0,23424.0,23424.0,2196.0
occupancy_rate,0.519244,0.519244,0.519244,0.519244,0.147692
total_discharges__v___xviii___xix___unknown_,1659.0,1659.0,1659.0,1659.0,62.0
total_days__v___xviii___xix___unknown_,11979.0,11979.0,11979.0,11979.0,288.0
fte___employees_on_payroll,295.42,295.42,295.42,295.42,52.5
net_patient_revenue,49431058.0,49431058.0,49431058.0,49431058.0,2126028.0
total_income,1931144.5,1931144.5,1931144.5,1931144.5,-682776.0
net_income,1583145.0,1583145.0,1583145.0,1583145.0,-682776.0
total_costs,42877261.0,42877261.0,42877261.0,42877261.0,3122896.0
total_other_expenses,148432.0,148432.0,148432.0,148432.0,148432.0
total_assets,49903957.5,49903957.5,49903957.5,49903957.5,1849854.0
total_liabilities,18897492.0,18897492.0,18897492.0,18897492.0,2984395.0
total_current_assets,15936809.0,15936809.0,15936809.0,15936809.0,1849854.0
total_current_liabilities,8253500.0,8253500.0,8253500.0,8253500.0,2984395.0
cash_on_hand_and_in_banks,1450362.0,1450362.0,1450362.0,1450362.0,19508.0
accounts_receivable,13052896.0,13052896.0,13052896.0,13052896.0,2757590.0
accounts_payable,2199589.5,2199589.5,2199589.5,2199589.5,230833.0
profit_margin_calc,0.046184,0.046184,0.046184,0.046184,-0.429478
cost_to_charge_ratio,0.318054,0.318054,0.318054,0.318054,0.677524
charity_care_ratio,0.016959,0.016959,0.016959,0.016959,0.138991
cost_of_charity_care,1281423.5,1281423.5,1281423.5,1281423.5,251283.0
total_unreimbursed_and_uncompensated_care,4373559.0,4373559.0,4373559.0,4373559.0,251283.0
medicare_cbsa_number,39740.0,39740.0,39740.0,39740.0,99901.0
type_of_control,"Proprietary, Corporation","Voluntary Non-Profit, Other","Government, City-County","Voluntary Non-Profit, Other","Voluntary Non-Profit, Other"
expense_ratio,0.867415,0.867415,0.867415,0.867415,1.468888
current_ratio,1.930915,1.930915,1.930915,1.930915,0.619842
debt_to_asset_ratio,0.378677,0.378677,0.378677,0.378677,1.613314
revenue_per_bed,748955.424242,748955.424242,748955.424242,748955.424242,85041.12
staff_to_bed_ratio,4.476061,4.476061,4.476061,4.476061,2.1
discharges_per_bed,25.136364,25.136364,25.136364,25.136364,2.48
avg_length_of_stay,7.220615,7.220615,7.220615,7.220615,4.645161
uncompensated_care_percent,10.200183,10.200183,10.200183,10.200183,8.046474
charity_care_percent,2.988585,2.988585,2.988585,2.988585,8.046474
rucc_code,2.0,2.0,2.0,2.0,6.0
rural_urban,Urban,Urban,Urban,Urban,Rural
fips,29127.0,29127.0,29127.0,29127.0,1013.0
population,159788.0,159788.0,159788.0,159788.0,20730.0
median_age,38.6,38.6,38.6,38.6,40.3
median_income,53176.0,53176.0,53176.0,53176.0,30752.0
poverty_rate,0.149096,0.149096,0.149096,0.149096,0.256854
higher_education_rate,0.261622,0.261622,0.261622,0.261622,0.128684
Other,70712.748026,61764.819949,65106.819338,61764.819949,53952.464444
wage_physician,155368.32636,185387.239336,170649.546742,185387.239336,192390.248447
wage_practitioner,83726.706945,78501.170093,79354.947692,78501.170093,79807.847264
wage_rn,74100.0,57520.0,58940.0,57520.0,55270.0
wage_support,29818.738535,27585.759055,26791.394178,27585.759055,24937.407102

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69555 entries, 0 to 69554
Data columns (total 51 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   year                                          69555 non-null  int64
 1   state_code                                    69555 non-null  object
 2   provider_type                                 69555 non-null  object
 3   ccn_facility_type                             69555 non-null  object
 4   number_of_beds                                69555 non-null  float64
 5   total_bed_days_available                      69555 non-null  float64
 6   occupancy_rate                                69555 non-null  float64
 7   total_discharges__v___xviii___xix___unknown_  69555 non-null  float64
 8   total_days__v___xviii___xix___unknown_        69555 non-null  float64
 9   fte___employees_on_payroll                    69555 non-null  float64
 10  net_patient_revenue                           69555 non-null  float64
 11  total_income                                  69555 non-null  float64
 12  net_income                                    69555 non-null  float64
 13  total_costs                                   69555 non-null  float64
 14  total_other_expenses                          69555 non-null  float64
 15  total_assets                                  69555 non-null  float64
 16  total_liabilities                             69555 non-null  float64
 17  total_current_assets                          69555 non-null  float64
 18  total_current_liabilities                     69555 non-null  float64
 19  cash_on_hand_and_in_banks                     69555 non-null  float64
 20  accounts_receivable                           69555 non-null  float64
 21  accounts_payable                              69555 non-null  float64
 22  profit_margin_calc                            69555 non-null  float64
 23  cost_to_charge_ratio                          69555 non-null  float64
 24  charity_care_ratio                            69555 non-null  float64
 25  cost_of_charity_care                          69555 non-null  float64
 26  total_unreimbursed_and_uncompensated_care     69555 non-null  float64
 27  medicare_cbsa_number                          69555 non-null  float64
 28  type_of_control                               69555 non-null  object
 29  expense_ratio                                 69555 non-null  float64
 30  current_ratio                                 69555 non-null  float64
 31  debt_to_asset_ratio                           69555 non-null  float64
 32  revenue_per_bed                               69555 non-null  float64
 33  staff_to_bed_ratio                            69555 non-null  float64
 34  discharges_per_bed                            69555 non-null  float64
 35  avg_length_of_stay                            69555 non-null  float64
 36  uncompensated_care_percent                    69555 non-null  float64
 37  charity_care_percent                          69555 non-null  float64
 38  rucc_code                                     69555 non-null  float64
 39  rural_urban                                   69555 non-null  object
 40  fips                                          69555 non-null  float64
 41  population                                    69555 non-null  float64
 42  median_age                                    69555 non-null  float64
 43  median_income                                 69555 non-null  float64
 44  poverty_rate                                  69555 non-null  float64
 45  higher_education_rate                         69555 non-null  float64
 46  Other                                         69555 non-null  float64
 47  wage_physician                                69555 non-null  float64
 48  wage_practitioner                             69555 non-null  float64
 49  wage_rn                                       69555 non-null  float64
 50  wage_support                                  69555 non-null  float64
dtypes: float64(45), int64(1), object(5)
memory usage: 27.1+ MB

In [4]:
# Sort by year
data = data.sort_values(by='year')

train_data = data[data['year'] <= 2019]
test_data = data[data['year'] > 2019]

In [6]:
targets = ['profit_margin_calc', 'charity_care_ratio']

In [7]:
models = {
    "Linear": LinearRegression(),
    "Ridge": Ridge(),
    "Lasso": Lasso(),
    "ElasticNet": ElasticNet(),
    "DecisionTree": DecisionTreeRegressor(),
    "RandomForest": RandomForestRegressor(random_state=42),
    "ExtraTrees": ExtraTreesRegressor(random_state=42),
    "GradientBoosting": GradientBoostingRegressor(),
    "KNN": KNeighborsRegressor(),
    "SVR": SVR()
}

In [8]:
def build_pipeline(X):
    cat_cols = X.select_dtypes(include=['object']).columns
    num_cols = X.select_dtypes(include=[np.number]).columns

    preprocessor = ColumnTransformer([
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols),
        ('num', 'passthrough', num_cols)
    ])

    return preprocessor

In [11]:
results = []

for target in targets:
    print("\nTARGET:", target, "\n")

    # Drop target from features to avoid leakage
    X_train = train_data.drop(targets, axis=1)
    y_train = train_data[target]

    X_test = test_data.drop(targets, axis=1)
    y_test = test_data[target]

    preprocessor = build_pipeline(X_train)

    for name, model in models.items():
        pipe = Pipeline([
            ('preprocessor', preprocessor),
            ('model', model)
        ])

        # Train
        pipe.fit(X_train, y_train)

        # Predictions
        y_train_pred = pipe.predict(X_train)
        y_test_pred = pipe.predict(X_test)

        # Metrics
        train_r2 = r2_score(y_train, y_train_pred)
        test_r2 = r2_score(y_test, y_test_pred)

        train_mse = mean_squared_error(y_train, y_train_pred)
        test_mse = mean_squared_error(y_test, y_test_pred)

        # Store results
        results.append({
            'Target': target,
            'Model': name,
            'Train_R2': train_r2,
            'Test_R2': test_r2,
            'Train_MSE': train_mse,
            'Test_MSE': test_mse
        })

        print(name)
        print("Train R2:", round(train_r2, 4), "MSE:", round(train_mse, 4))
        print("Test  R2:", round(test_r2, 4), "MSE:", round(test_mse, 4))
        print("-" * 50)

# Create dataframe
results_df = pd.DataFrame(results)

# Sort results
results_df = results_df.sort_values(
    by=['Target', 'Test_R2'],
    ascending=[True, False]
).reset_index(drop=True)

# Round values
results_df = results_df.round({
    'Train_R2': 4,
    'Test_R2': 4,
    'Train_MSE': 2,
    'Test_MSE': 2
})

# Overfitting gap
results_df['Overfit_Gap'] = (results_df['Train_R2'] - results_df['Test_R2']).round(4)

# Best models per target
best_models = results_df.loc[results_df.groupby('Target')['Test_R2'].idxmax()]

results_df
best_models

TARGET: profit_margin_calc

Linear
Train R2: 0.3487 MSE: 0.02
Test  R2: 0.2922 MSE: 0.0288
--------------------------------------------------

c:\Users\manju\AppData\Local\Programs\Python\Python313\Lib\site-packages\scipy\_lib\_util.py:1233: LinAlgWarning: Ill-conditioned matrix (rcond=3.44776e-23): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)

Ridge
Train R2: 0.3487 MSE: 0.02
Test  R2: 0.2922 MSE: 0.0288
--------------------------------------------------
Lasso
Train R2: 0.2194 MSE: 0.024
Test  R2: 0.1996 MSE: 0.0326
--------------------------------------------------
ElasticNet
Train R2: 0.2194 MSE: 0.024
Test  R2: 0.1984 MSE: 0.0326
--------------------------------------------------
DecisionTree
Train R2: 1.0 MSE: 0.0
Test  R2: 0.8124 MSE: 0.0076
--------------------------------------------------
RandomForest
Train R2: 0.9925 MSE: 0.0002
Test  R2: 0.9301 MSE: 0.0028
--------------------------------------------------
ExtraTrees
Train R2: 1.0 MSE: 0.0
Test  R2: 0.9155 MSE: 0.0034
--------------------------------------------------
GradientBoosting
Train R2: 0.8634 MSE: 0.0042
Test  R2: 0.8377 MSE: 0.0066
--------------------------------------------------
KNN
Train R2: 0.8315 MSE: 0.0052
Test  R2: 0.6543 MSE: 0.0141
--------------------------------------------------
SVR
Train R2: 0.432 MSE: 0.0175
Test  R2: 0.4568 MSE: 0.0221
--------------------------------------------------

TARGET: charity_care_ratio

Linear
Train R2: 0.622 MSE: 0.0003
Test  R2: 0.5708 MSE: 0.0003
--------------------------------------------------

c:\Users\manju\AppData\Local\Programs\Python\Python313\Lib\site-packages\scipy\_lib\_util.py:1233: LinAlgWarning: Ill-conditioned matrix (rcond=3.44776e-23): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)

Ridge
Train R2: 0.622 MSE: 0.0003
Test  R2: 0.571 MSE: 0.0003
--------------------------------------------------
Lasso
Train R2: 0.448 MSE: 0.0005
Test  R2: 0.321 MSE: 0.0005
--------------------------------------------------
ElasticNet
Train R2: 0.4487 MSE: 0.0005
Test  R2: 0.3234 MSE: 0.0005
--------------------------------------------------
DecisionTree
Train R2: 1.0 MSE: 0.0
Test  R2: 0.9837 MSE: 0.0
--------------------------------------------------
RandomForest
Train R2: 0.9994 MSE: 0.0
Test  R2: 0.9898 MSE: 0.0
--------------------------------------------------
ExtraTrees
Train R2: 1.0 MSE: 0.0
Test  R2: 0.9881 MSE: 0.0
--------------------------------------------------
GradientBoosting
Train R2: 0.9954 MSE: 0.0
Test  R2: 0.9892 MSE: 0.0
--------------------------------------------------
KNN
Train R2: 0.6309 MSE: 0.0003
Test  R2: 0.1607 MSE: 0.0007
--------------------------------------------------
SVR
Train R2: -5.0658 MSE: 0.0053
Test  R2: -5.8319 MSE: 0.0053
--------------------------------------------------

,Target,Model,Train_R2,Test_R2,Train_MSE,Test_MSE,Overfit_Gap
0,charity_care_ratio,RandomForest,0.9994,0.9898,0.0,0.0,0.0096
10,profit_margin_calc,RandomForest,0.9925,0.9301,0.0,0.0,0.0624

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import TimeSeriesSplit, GridSearchCV
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, ExtraTreesRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

# sort and split
data = data.sort_values(by='year')

train_data = data[data['year'] <= 2019]
test_data = data[data['year'] > 2019]

targets = ['profit_margin_calc', 'charity_care_ratio']

# preprocessing
def build_preprocessor(X):
    cat_cols = X.select_dtypes(include=['object']).columns
    num_cols = X.select_dtypes(include=[np.number]).columns

    return ColumnTransformer([
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_cols),
        ('num', 'passthrough', num_cols)
    ])

# models and grids
models_and_params = {
    "Linear": (
        LinearRegression(),
        {}
    ),
    "Ridge": (
        Ridge(),
        {'model__alpha': [0.1, 1.0, 10]}
    ),
    "Lasso": (
        Lasso(),
        {'model__alpha': [0.001, 0.01, 0.1]}
    ),
    "ElasticNet": (
        ElasticNet(),
        {
            'model__alpha': [0.001, 0.01],
            'model__l1_ratio': [0.3, 0.5, 0.7]
        }
    ),
    "DecisionTree": (
        DecisionTreeRegressor(random_state=42),
        {
            'model__max_depth': [5, 8, 10],
            'model__min_samples_leaf': [1, 5, 10]
        }
    ),
    "RandomForest": (
        RandomForestRegressor(random_state=42),
        {
            'model__n_estimators': [100, 200],
            'model__max_depth': [8, 10],
            'model__min_samples_leaf': [1, 5]
        }
    ),
    "ExtraTrees": (
        ExtraTreesRegressor(random_state=42),
        {
            'model__n_estimators': [100, 200],
            'model__max_depth': [8, 10],
            'model__min_samples_leaf': [1, 5]
        }
    ),
    "GradientBoosting": (
        GradientBoostingRegressor(),
        {
            'model__n_estimators': [100, 200],
            'model__learning_rate': [0.05, 0.1],
            'model__max_depth': [3, 5]
        }
    ),
    "KNN": (
        KNeighborsRegressor(),
        {
            'model__n_neighbors': [5, 10],
            'model__weights': ['uniform', 'distance']
        }
    ),
    "SVR": (
        SVR(),
        {
            'model__C': [1, 10],
            'model__kernel': ['rbf'],
            'model__gamma': ['scale']
        }
    )
}

# cross validation
tscv = TimeSeriesSplit(n_splits=5)

results = []

# training loop
for target in targets:
    print("\nTARGET:", target, "\n")

    X_train = train_data.drop(targets, axis=1)
    y_train = train_data[target]

    X_test = test_data.drop(targets, axis=1)
    y_test = test_data[target]

    preprocessor = build_preprocessor(X_train)

    for name, (model, param_grid) in models_and_params.items():

        pipe = Pipeline([
            ('preprocessor', preprocessor),
            ('model', model)
        ])

        grid = GridSearchCV(
            pipe,
            param_grid,
            cv=tscv,
            scoring='r2',
            n_jobs=-1
        )

        grid.fit(X_train, y_train)

        best_model = grid.best_estimator_

        y_train_pred = best_model.predict(X_train)
        y_test_pred = best_model.predict(X_test)

        train_r2 = r2_score(y_train, y_train_pred)
        test_r2 = r2_score(y_test, y_test_pred)

        train_mse = mean_squared_error(y_train, y_train_pred)
        test_mse = mean_squared_error(y_test, y_test_pred)

        train_mae = mean_absolute_error(y_train, y_train_pred)
        test_mae = mean_absolute_error(y_test, y_test_pred)

        results.append({
            'Target': target,
            'Model': name,
            'Best_Params': grid.best_params_,
            'CV_Score': grid.best_score_,
            'Train_R2': train_r2,
            'Test_R2': test_r2,
            'Train_MSE': train_mse,
            'Test_MSE': test_mse,
            'Train_MAE': train_mae,
            'Test_MAE': test_mae
        })

        print(name)
        print("Best Params:", grid.best_params_)
        print("CV R2:", round(grid.best_score_, 4))
        print("Train R2:", round(train_r2, 4), "Test R2:", round(test_r2, 4))
        print("-" * 50)

# results dataframe
results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by=['Target', 'Test_R2'],
    ascending=[True, False]
).reset_index(drop=True)

results_df = results_df.round(4)

results_df['Overfit_Gap'] = (results_df['Train_R2'] - results_df['Test_R2']).round(4)

print("\nFINAL RESULTS\n")
print(results_df)

# best models
best_models = results_df.loc[results_df.groupby('Target')['Test_R2'].idxmax()]

print("\nBEST MODELS\n")
print(best_models)

TARGET: profit_margin_calc

Linear
Best Params: {}
CV R2: 0.3281
Train R2: 0.3487 Test R2: 0.2922
--------------------------------------------------

c:\Users\manju\AppData\Local\Programs\Python\Python313\Lib\site-packages\scipy\_lib\_util.py:1233: LinAlgWarning: Ill-conditioned matrix (rcond=3.39087e-22): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)

Ridge
Best Params: {'model__alpha': 10}
CV R2: 0.329
Train R2: 0.3487 Test R2: 0.2922
--------------------------------------------------

c:\Users\manju\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.969e+01, tolerance: 1.565e-01
  model = cd_fast.enet_coordinate_descent(

Lasso
Best Params: {'model__alpha': 0.001}
CV R2: 0.312
Train R2: 0.3281 Test R2: 0.2829
--------------------------------------------------

c:\Users\manju\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.650e-01, tolerance: 1.565e-01
  model = cd_fast.enet_coordinate_descent(

ElasticNet
Best Params: {'model__alpha': 0.001, 'model__l1_ratio': 0.3}
CV R2: 0.323
Train R2: 0.3407 Test R2: 0.2902
--------------------------------------------------
DecisionTree
Best Params: {'model__max_depth': 10, 'model__min_samples_leaf': 10}
CV R2: 0.8341
Train R2: 0.9285 Test R2: 0.8716
--------------------------------------------------
RandomForest
Best Params: {'model__max_depth': 10, 'model__min_samples_leaf': 1, 'model__n_estimators': 200}
CV R2: 0.8862
Train R2: 0.966 Test R2: 0.9144
--------------------------------------------------
ExtraTrees
Best Params: {'model__max_depth': 10, 'model__min_samples_leaf': 1, 'model__n_estimators': 100}
CV R2: 0.7765
Train R2: 0.8474 Test R2: 0.777
--------------------------------------------------
GradientBoosting
Best Params: {'model__learning_rate': 0.1, 'model__max_depth': 5, 'model__n_estimators': 200}
CV R2: 0.9088
Train R2: 0.9901 Test R2: 0.9437
--------------------------------------------------
KNN
Best Params: {'model__n_neighbors': 5, 'model__weights': 'distance'}
CV R2: 0.645
Train R2: 1.0 Test R2: 0.6623
--------------------------------------------------
SVR
Best Params: {'model__C': 10, 'model__gamma': 'scale', 'model__kernel': 'rbf'}
CV R2: 0.4749
Train R2: 0.51 Test R2: 0.5277
--------------------------------------------------

TARGET: charity_care_ratio

Linear
Best Params: {}
CV R2: 0.6063
Train R2: 0.622 Test R2: 0.5708
--------------------------------------------------

c:\Users\manju\AppData\Local\Programs\Python\Python313\Lib\site-packages\scipy\_lib\_util.py:1233: LinAlgWarning: Ill-conditioned matrix (rcond=3.39087e-22): result may not be accurate.
  return f(*arrays, *other_args, **kwargs)

Ridge
Best Params: {'model__alpha': 10}
CV R2: 0.6072
Train R2: 0.6219 Test R2: 0.5723
--------------------------------------------------
Lasso
Best Params: {'model__alpha': 0.001}
CV R2: 0.5241
Train R2: 0.5393 Test R2: 0.4721
--------------------------------------------------
ElasticNet
Best Params: {'model__alpha': 0.001, 'model__l1_ratio': 0.3}
CV R2: 0.5476
Train R2: 0.5643 Test R2: 0.5085
--------------------------------------------------
DecisionTree
Best Params: {'model__max_depth': 10, 'model__min_samples_leaf': 5}
CV R2: 0.9872
Train R2: 0.998 Test R2: 0.9851
--------------------------------------------------
RandomForest
Best Params: {'model__max_depth': 10, 'model__min_samples_leaf': 1, 'model__n_estimators': 200}
CV R2: 0.9928
Train R2: 0.9991 Test R2: 0.9892
--------------------------------------------------
ExtraTrees
Best Params: {'model__max_depth': 10, 'model__min_samples_leaf': 1, 'model__n_estimators': 200}
CV R2: 0.9662
Train R2: 0.9767 Test R2: 0.9605
--------------------------------------------------
GradientBoosting
Best Params: {'model__learning_rate': 0.05, 'model__max_depth': 5, 'model__n_estimators': 200}
CV R2: 0.994
Train R2: 0.9994 Test R2: 0.9923
--------------------------------------------------
KNN
Best Params: {'model__n_neighbors': 5, 'model__weights': 'distance'}
CV R2: 0.3024
Train R2: 1.0 Test R2: 0.177
--------------------------------------------------
SVR
Best Params: {'model__C': 1, 'model__gamma': 'scale', 'model__kernel': 'rbf'}
CV R2: -5.0558
Train R2: -5.0658 Test R2: -5.8319
--------------------------------------------------

FINAL RESULTS

                Target             Model  \
0   charity_care_ratio  GradientBoosting
1   charity_care_ratio      RandomForest
2   charity_care_ratio      DecisionTree
3   charity_care_ratio        ExtraTrees
4   charity_care_ratio             Ridge
5   charity_care_ratio            Linear
6   charity_care_ratio        ElasticNet
7   charity_care_ratio             Lasso
8   charity_care_ratio               KNN
9   charity_care_ratio               SVR
10  profit_margin_calc  GradientBoosting
11  profit_margin_calc      RandomForest
12  profit_margin_calc      DecisionTree
13  profit_margin_calc        ExtraTrees
14  profit_margin_calc               KNN
15  profit_margin_calc               SVR
16  profit_margin_calc            Linear
17  profit_margin_calc             Ridge
18  profit_margin_calc        ElasticNet
19  profit_margin_calc             Lasso

                                          Best_Params  CV_Score  Train_R2  \
0   {'model__learning_rate': 0.05, 'model__max_dep...    0.9940    0.9994
1   {'model__max_depth': 10, 'model__min_samples_l...    0.9928    0.9991
2   {'model__max_depth': 10, 'model__min_samples_l...    0.9872    0.9980
3   {'model__max_depth': 10, 'model__min_samples_l...    0.9662    0.9767
4                                {'model__alpha': 10}    0.6072    0.6219
5                                                  {}    0.6063    0.6220
6     {'model__alpha': 0.001, 'model__l1_ratio': 0.3}    0.5476    0.5643
7                             {'model__alpha': 0.001}    0.5241    0.5393
8   {'model__n_neighbors': 5, 'model__weights': 'd...    0.3024    1.0000
9   {'model__C': 1, 'model__gamma': 'scale', 'mode...   -5.0558   -5.0658
10  {'model__learning_rate': 0.1, 'model__max_dept...    0.9088    0.9901
11  {'model__max_depth': 10, 'model__min_samples_l...    0.8862    0.9660
12  {'model__max_depth': 10, 'model__min_samples_l...    0.8341    0.9285
13  {'model__max_depth': 10, 'model__min_samples_l...    0.7765    0.8474
14  {'model__n_neighbors': 5, 'model__weights': 'd...    0.6450    1.0000
15  {'model__C': 10, 'model__gamma': 'scale', 'mod...    0.4749    0.5100
16                                                 {}    0.3281    0.3487
17                               {'model__alpha': 10}    0.3290    0.3487
18    {'model__alpha': 0.001, 'model__l1_ratio': 0.3}    0.3230    0.3407
19                            {'model__alpha': 0.001}    0.3120    0.3281

    Test_R2  Train_MSE  Test_MSE  Train_MAE  Test_MAE  Overfit_Gap
0    0.9923     0.0000    0.0000     0.0003    0.0004       0.0071
1    0.9892     0.0000    0.0000     0.0002    0.0004       0.0099
2    0.9851     0.0000    0.0000     0.0002    0.0004       0.0129
3    0.9605     0.0000    0.0000     0.0016    0.0019       0.0162
4    0.5723     0.0003    0.0003     0.0119    0.0118       0.0496
5    0.5708     0.0003    0.0003     0.0119    0.0118       0.0512
6    0.5085     0.0004    0.0004     0.0124    0.0123       0.0558
7    0.4721     0.0004    0.0004     0.0126    0.0125       0.0672
8    0.1770     0.0000    0.0006     0.0000    0.0154       0.8230
9   -5.8319     0.0053    0.0053     0.0696    0.0702       0.7661
10   0.9437     0.0003    0.0023     0.0089    0.0160       0.0464
11   0.9144     0.0010    0.0035     0.0105    0.0197       0.0516
12   0.8716     0.0022    0.0052     0.0175    0.0285       0.0569
13   0.7770     0.0047    0.0091     0.0360    0.0503       0.0704
14   0.6623     0.0000    0.0138     0.0000    0.0675       0.3377
15   0.5277     0.0151    0.0192     0.0698    0.0821      -0.0177
16   0.2922     0.0200    0.0288     0.0844    0.1092       0.0565
17   0.2922     0.0200    0.0288     0.0844    0.1092       0.0565
18   0.2902     0.0203    0.0289     0.0841    0.1087       0.0505
19   0.2829     0.0207    0.0292     0.0848    0.1094       0.0452

BEST MODELS

                Target             Model  \
0   charity_care_ratio  GradientBoosting
10  profit_margin_calc  GradientBoosting

                                          Best_Params  CV_Score  Train_R2  \
0   {'model__learning_rate': 0.05, 'model__max_dep...    0.9940    0.9994
10  {'model__learning_rate': 0.1, 'model__max_dept...    0.9088    0.9901

    Test_R2  Train_MSE  Test_MSE  Train_MAE  Test_MAE  Overfit_Gap
0    0.9923     0.0000    0.0000     0.0003    0.0004       0.0071
10   0.9437     0.0003    0.0023     0.0089    0.0160       0.0464

In [ ]:
# Feature importance for best model of profit_margin_calc
best_profit_model_name = best_models[best_models['Target'] == 'profit_margin_calc']['Model'].values[0]
best_profit_model_params = best_models[best_models['Target'] == 'profit_margin_calc']['Best_Params'].values[0]
print("Best Model for profit_margin_calc:", best_profit_model_name)
print("Best Hyperparameters:", best_profit_model_params)

NameError: name 'best_models' is not defined

In [13]:
# FEATURE SELECTION (RandomForest)

from sklearn.ensemble import RandomForestRegressor

# use one target for feature importance (you can change this)
target = 'profit_margin_calc'

X_train_full = train_data.drop(targets, axis=1)
y_train_full = train_data[target]

# preprocess once to get feature names
preprocessor = build_preprocessor(X_train_full)
X_train_transformed = preprocessor.fit_transform(X_train_full)

# get feature names
cat_cols = X_train_full.select_dtypes(include=['object']).columns
num_cols = X_train_full.select_dtypes(include=[np.number]).columns

ohe = preprocessor.named_transformers_['cat']
cat_feature_names = ohe.get_feature_names_out(cat_cols)

feature_names = np.concatenate([cat_feature_names, num_cols])

# train RF for importance
rf = RandomForestRegressor(n_estimators=200, random_state=42)
rf.fit(X_train_transformed, y_train_full)

importances = pd.DataFrame({
    'Feature': feature_names,
    'Importance': rf.feature_importances_
}).sort_values(by='Importance', ascending=False)

# select top features (change threshold or top N)
top_features = importances.head(30)['Feature'].tolist()

print("Selected Features:", len(top_features))

# TRANSFORM DATA WITH SELECTED FEATURES

def transform_with_selected_features(X, preprocessor, selected_features):
    X_transformed = preprocessor.transform(X)
    df_transformed = pd.DataFrame(X_transformed, columns=feature_names, index=X.index)
    return df_transformed[selected_features]

# RERUN MODELS WITH SELECTED FEATURES

results_selected = []

tscv = TimeSeriesSplit(n_splits=5)

for target in targets:
    print("\nTARGET (SELECTED FEATURES):", target, "\n")

    X_train = train_data.drop(targets, axis=1)
    y_train = train_data[target]

    X_test = test_data.drop(targets, axis=1)
    y_test = test_data[target]

    # transform using selected features
    X_train_sel = transform_with_selected_features(X_train, preprocessor, top_features)
    X_test_sel = transform_with_selected_features(X_test, preprocessor, top_features)

    for name, (model, param_grid) in models_and_params.items():

        grid = GridSearchCV(
            model,
            param_grid,
            cv=tscv,
            scoring='r2',
            n_jobs=-1
        )

        grid.fit(X_train_sel, y_train)

        best_model = grid.best_estimator_

        y_train_pred = best_model.predict(X_train_sel)
        y_test_pred = best_model.predict(X_test_sel)

        train_r2 = r2_score(y_train, y_train_pred)
        test_r2 = r2_score(y_test, y_test_pred)

        train_mse = mean_squared_error(y_train, y_train_pred)
        test_mse = mean_squared_error(y_test, y_test_pred)

        results_selected.append({
            'Target': target,
            'Model': name,
            'Train_R2': train_r2,
            'Test_R2': test_r2,
            'Train_MSE': train_mse,
            'Test_MSE': test_mse
        })

        print(name, "Train R2:", round(train_r2, 4), "Test R2:", round(test_r2, 4))

# results
results_selected_df = pd.DataFrame(results_selected)

results_selected_df = results_selected_df.sort_values(
    by=['Target', 'Test_R2'],
    ascending=[True, False]
).reset_index(drop=True)

results_selected_df['Overfit_Gap'] = (
    results_selected_df['Train_R2'] - results_selected_df['Test_R2']
).round(4)

print("\nRESULTS WITH SELECTED FEATURES\n")
print(results_selected_df)

Selected Features: 30

TARGET (SELECTED FEATURES): profit_margin_calc

Linear Train R2: 0.3193 Test R2: 0.277

ValueError: Invalid parameter 'model' for estimator Ridge(). Valid parameters are: ['alpha', 'copy_X', 'fit_intercept', 'max_iter', 'positive', 'random_state', 'solver', 'tol'].

In [ ]:
# export full results
results_df.to_csv("model_results_full.csv", index=False)

# export best models
best_models.to_csv("best_models.csv", index=False)

# export feature-selected results
results_selected_df.to_csv("model_results_selected_features.csv", index=False)

# export feature importance
importances.to_csv("feature_importance.csv", index=False)

print("\nFiles exported successfully")

In [ ]:
import joblib
import os

os.makedirs("saved_models", exist_ok=True)

for i, row in best_models.iterrows():
    target = row['Target']
    model_name = row['Model']
    
    # you must store models in loop to access them here
    # assume you saved them in a dictionary called best_model_objects
    
    model = best_model_objects[(target, model_name)]
    
    filename = f"saved_models/best_{target}_{model_name}.pkl"
    joblib.dump(model, filename)

print("All best models saved")