In [1]:
import pandas as pd
import numpy as np

In [2]:
hospital = pd.read_csv(r"C:\Users\manju\OneDrive\Desktop\Documents\Data Analytics\DA Semester 4\Capstone 2\ML Modelling\hospital_kpi_ready_with_rucc.csv")
hospital.head()

,year,state_code,provider_type,ccn_facility_type,number_of_beds,total_bed_days_available,occupancy_rate,total_discharges__v___xviii___xix___unknown_,total_days__v___xviii___xix___unknown_,fte___employees_on_payroll,...,current_ratio,debt_to_asset_ratio,revenue_per_bed,staff_to_bed_ratio,discharges_per_bed,avg_length_of_stay,uncompensated_care_percent,charity_care_percent,rucc_code,rural_urban
0,2011,AL,General Short-Term (includes CAH),Short-Term Hospital,114.0,41610.0,0.472026,5283.0,19641.0,598.72,...,15.215095,0.127844,555364.719298,5.251930,46.342105,3.717774,2.482716,2.263904,4.0,Rural
1,2011,MT,General Short-Term (includes CAH),Critical Access Hospital,25.0,9125.0,0.131068,155.0,1196.0,70.56,...,5.658947,0.780058,346468.920000,2.822400,6.200000,7.716129,9.372838,2.320308,3.0,Urban
2,2011,AL,General Short-Term (includes CAH),Short-Term Hospital,46.0,16790.0,0.159678,892.0,2681.0,72.65,...,2.102318,0.360171,285858.847826,1.579348,19.391304,3.005605,15.092862,10.117954,6.0,Rural
3,2011,AL,Rehabilitation Hospital,Rehabilitation Hospital,100.0,36500.0,0.887068,2390.0,32378.0,297.77,...,25.351430,0.073603,395544.200000,2.977700,23.900000,13.547280,-0.031671,4.613961,1.0,Urban
4,2011,FL,Rehabilitation Hospital,Rehabilitation Hospital,70.0,25550.0,0.663836,1370.0,16961.0,154.60,...,21.567746,0.040220,289171.742857,2.208571,19.571429,12.380292,-0.090532,7.756714,1.0,Urban

In [3]:
bls_healthcare = pd.read_csv(r"C:\Users\manju\OneDrive\Desktop\Documents\Data Analytics\DA Semester 4\Capstone 2\Supplementary Data\bls_healthcare_grouped.csv")
bls_healthcare.head()

,year,state_code,occ_code,occ_title,tot_emp,a_mean,occupation_group
0,2011,AL,29-1011,Chiropractors,230.0,75320.0,Practitioner
1,2011,AL,29-1021,"Dentists, General",820.0,205130.0,Other
2,2011,AL,29-1023,Orthodontists,70.0,204560.0,Other
3,2011,AL,29-1029,"Dentists, All Other Specialists",50.0,193120.0,Other
4,2011,AL,29-1031,Dietitians and Nutritionists,650.0,49540.0,Practitioner

In [4]:
# Merge BLS wages into CMS hospital data
hospital_with_wages = hospital.merge(
    bls_healthcare,
    on=["year", "state_code"],
    how="left"
)
print("Merged dataset shape:", hospital_with_wages.shape)
hospital_with_wages.head()

Merged dataset shape: (5079348, 50)

,year,state_code,provider_type,ccn_facility_type,number_of_beds,total_bed_days_available,occupancy_rate,total_discharges__v___xviii___xix___unknown_,total_days__v___xviii___xix___unknown_,fte___employees_on_payroll,...,avg_length_of_stay,uncompensated_care_percent,charity_care_percent,rucc_code,rural_urban,occ_code,occ_title,tot_emp,a_mean,occupation_group
0,2011,AL,General Short-Term (includes CAH),Short-Term Hospital,114.0,41610.0,0.472026,5283.0,19641.0,598.72,...,3.717774,2.482716,2.263904,4.0,Rural,29-1011,Chiropractors,230.0,75320.0,Practitioner
1,2011,AL,General Short-Term (includes CAH),Short-Term Hospital,114.0,41610.0,0.472026,5283.0,19641.0,598.72,...,3.717774,2.482716,2.263904,4.0,Rural,29-1021,"Dentists, General",820.0,205130.0,Other
2,2011,AL,General Short-Term (includes CAH),Short-Term Hospital,114.0,41610.0,0.472026,5283.0,19641.0,598.72,...,3.717774,2.482716,2.263904,4.0,Rural,29-1023,Orthodontists,70.0,204560.0,Other
3,2011,AL,General Short-Term (includes CAH),Short-Term Hospital,114.0,41610.0,0.472026,5283.0,19641.0,598.72,...,3.717774,2.482716,2.263904,4.0,Rural,29-1029,"Dentists, All Other Specialists",50.0,193120.0,Other
4,2011,AL,General Short-Term (includes CAH),Short-Term Hospital,114.0,41610.0,0.472026,5283.0,19641.0,598.72,...,3.717774,2.482716,2.263904,4.0,Rural,29-1031,Dietitians and Nutritionists,650.0,49540.0,Practitioner

In [5]:
hospital_with_wages[["rucc_code", "rural_urban"]].isna().mean()

rucc_code      0.083798
rural_urban    0.083798
dtype: float64

In [ ]:
# How many occupation groups per hospital-year?
hospital_with_wages["occupation_group"].value_counts()

# Check duplication logic
hospital_with_wages.groupby(
    ["year", "state_code", "hospital_name"]
).size().value_counts().head()

77    12738
76     7762
1      5789
75     4728
67     3833
Name: count, dtype: int64

In [7]:
# Save the merged dataset
hospital_with_wages.to_csv(
    r"C:\Users\manju\OneDrive\Desktop\Documents\Data Analytics\DA Semester 4\Capstone 2\ML Modelling\hospital_kpi_with_bls_wages.csv",
    index=False
)