In [1]:
import numpy as np
import pandas as pd

In [2]:
hospital = pd.read_csv(r"C:\Users\manju\OneDrive\Desktop\Documents\Data Analytics\DA Semester 4\Capstone 2\Supplementary Data\hospital_kpi_ready.csv")
hospital.head().T

,0,1,2,3,4
year,2011,2011,2011,2011,2011
state_code,AL,MT,AL,AL,FL
provider_type,General Short-Term (includes CAH),General Short-Term (includes CAH),General Short-Term (includes CAH),Rehabilitation Hospital,Rehabilitation Hospital
rural_versus_urban,Rural,Rural,Urban,Urban,Urban
ccn_facility_type,Short-Term Hospital,Critical Access Hospital,Short-Term Hospital,Rehabilitation Hospital,Rehabilitation Hospital
number_of_beds,114.0,25.0,46.0,100.0,70.0
total_bed_days_available,41610.0,9125.0,16790.0,36500.0,25550.0
occupancy_rate,0.472026,0.131068,0.159678,0.887068,0.663836
total_discharges__v___xviii___xix___unknown_,5283.0,155.0,892.0,2390.0,1370.0
total_days__v___xviii___xix___unknown_,19641.0,1196.0,2681.0,32378.0,16961.0
fte___employees_on_payroll,598.72,70.56,72.65,297.77,154.6
net_patient_revenue,63311578.0,8661723.0,13149507.0,39554420.0,20242022.0
total_income,-2691671.0,-837408.0,132630.0,11784376.0,4565066.0
net_income,-2691671.0,-837408.0,132630.0,11762647.0,4565066.0
total_costs,57980457.0,8826889.0,12664848.0,27772742.0,16520185.0
total_other_expenses,148432.0,148432.0,148432.0,21729.0,148432.0
total_assets,109224801.0,23319725.0,3634507.0,83044000.0,49107070.0
total_liabilities,13963740.0,18190741.0,1309043.0,6112321.0,1975069.0
total_current_assets,15310555.0,4766124.0,2895733.0,77489587.0,42597787.0
total_current_liabilities,1006274.0,842228.0,1377400.0,3056616.0,1975069.0
cash_on_hand_and_in_banks,6878054.0,933246.0,850541.0,73289485.0,40782630.0
accounts_receivable,6379506.0,2832699.0,4915619.0,4851517.0,1969952.0
accounts_payable,4100999.0,61242.0,1197880.0,524898.0,973226.0
profit_margin_calc,-0.042515,-0.096679,0.010086,0.297379,0.225524
cost_to_charge_ratio,0.282971,1.061421,0.641784,0.452421,0.663245
charity_care_ratio,0.022639,0.023203,0.016959,0.016959,0.016959
cost_of_charity_care,1312622.0,204811.0,1281423.5,1281423.5,1281423.5
total_unreimbursed_and_uncompensated_care,1439490.0,827330.0,1911488.0,-8796.0,-14956.0
hospital_name,Marshall Medical Center - South,Beartooth Billings Clinic,Lake Martin Community Hospital,Healthsouth Lakeshore Hospital,Healthsouth Rehabilitation Hospital
city,Boaz,Red Lodge,Dadeville,Birmingham,Largo
county,Marshall,Carbon,Tallapoosa,Jefferson,Pinellas
zip_code,35957,59806,36853,35209,33770
medicare_cbsa_number,13820.0,99927.0,99919.0,13820.0,45300.0
type_of_control,"Government, County","Voluntary Non-Profit, Other","Proprietary, Partnership","Proprietary, Corporation","Proprietary, Corporation"
state_full_name,Alabama,Montana,Alabama,Alabama,Florida
expense_ratio,0.915795,1.019068,0.963142,0.70214,0.816133
current_ratio,15.215095,5.658947,2.102318,25.35143,21.567746
debt_to_asset_ratio,0.127844,0.780058,0.360171,0.073603,0.04022
revenue_per_bed,555364.719298,346468.92,285858.847826,395544.2,289171.742857
staff_to_bed_ratio,5.25193,2.8224,1.579348,2.9777,2.208571
discharges_per_bed,46.342105,6.2,19.391304,23.9,19.571429
avg_length_of_stay,3.717774,7.716129,3.005605,13.54728,12.380292
uncompensated_care_percent,2.482716,9.372838,15.092862,-0.031671,-0.090532
charity_care_percent,2.263904,2.320308,10.117954,4.613961,7.756714

In [3]:
rucc_raw = pd.read_csv(r"C:\Users\manju\OneDrive\Desktop\Documents\Data Analytics\DA Semester 4\Capstone 2\Supplementary Data\rural_urban_codes.csv",encoding='latin1')
rucc_raw.head()

,FIPS,State,County_Name,Attribute,Value
0,1001,AL,Autauga County,Population_2020,58805
1,1001,AL,Autauga County,RUCC_2023,2
2,1001,AL,Autauga County,Description,"Metro - Counties in metro areas of 250,000 to ..."
3,1003,AL,Baldwin County,Population_2020,231767
4,1003,AL,Baldwin County,RUCC_2023,3

In [ ]:
# Function to clean county names
import re

def clean_county(x):
    x = str(x).upper().strip()
    x = re.sub(r"\s+(COUNTY|MUNICIPIO|PARISH|BOROUGH|CENSUS AREA|ISLAND|CITY)$", "", x)
    x = x.replace("SAINT ", "ST ")
    x = re.sub(r"[^\w\s]", "", x)
    return x.strip()

In [ ]:
# CMS
hospital["county_key"] = hospital["county"].apply(clean_county)
hospital["state_key"] = hospital["state_code"].str.upper()

# RUCC 
rucc = rucc_raw.copy()
rucc.columns = rucc.columns.str.strip()

# Filter for RUCC 2023 attribute and valid numeric values
rucc = rucc[rucc["Attribute"] == "RUCC_2023"]
rucc = rucc[rucc["Value"].astype(str).str.isdigit()]

# Clean county and state keys
rucc["county_key"] = rucc["County_Name"].apply(clean_county)
rucc["state_key"] = rucc["State"].str.upper()
# Create RUCC code and rural/urban classification
rucc["rucc_code"] = rucc["Value"].astype(int)
rucc["rural_urban"] = rucc["rucc_code"].apply(
    lambda x: "Urban" if x <= 3 else "Rural"
)
# Select relevant columns
rucc = rucc[["state_key", "county_key", "rucc_code", "rural_urban"]]

In [ ]:
# Check overlap of county keys in Alabama
cms_al = set(hospital[hospital["state_key"]=="AL"]["county_key"])
rucc_al = set(rucc[rucc["state_key"]=="AL"]["county_key"])
cms_al & rucc_al

{'AUTAUGA',
 'BALDWIN',
 'BARBOUR',
 'BIBB',
 'BLOUNT',
 'BULLOCK',
 'BUTLER',
 'CALHOUN',
 'CHAMBERS',
 'CHEROKEE',
 'CHILTON',
 'CLARKE',
 'CLAY',
 'COFFEE',
 'COLBERT',
 'CONECUH',
 'COVINGTON',
 'CRENSHAW',
 'CULLMAN',
 'DALE',
 'DALLAS',
 'DEKALB',
 'ELMORE',
 'ESCAMBIA',
 'ETOWAH',
 'FAYETTE',
 'FRANKLIN',
 'GENEVA',
 'GREENE',
 'HALE',
 'HOUSTON',
 'JACKSON',
 'JEFFERSON',
 'LAUDERDALE',
 'LAWRENCE',
 'LEE',
 'LIMESTONE',
 'MADISON',
 'MARENGO',
 'MARION',
 'MARSHALL',
 'MOBILE',
 'MONROE',
 'MONTGOMERY',
 'MORGAN',
 'PICKENS',
 'PIKE',
 'RANDOLPH',
 'RUSSELL',
 'SHELBY',
 'ST CLAIR',
 'SUMTER',
 'TALLADEGA',
 'TALLAPOOSA',
 'TUSCALOOSA',
 'WALKER',
 'WASHINGTON',
 'WILCOX',
 'WINSTON'}

In [ ]:
# Merge RUCC data into hospital dataset
hospital = hospital.merge(
    rucc,
    on=["state_key", "county_key"],
    how="left"
).drop(columns=["state_key", "county_key"])

In [13]:
# Dropping rural_versus_urban column as not needed
hospital = hospital.drop(columns=["rural_versus_urban"])
hospital.head().T

,0,1,2,3,4
year,2011,2011,2011,2011,2011
state_code,AL,MT,AL,AL,FL
provider_type,General Short-Term (includes CAH),General Short-Term (includes CAH),General Short-Term (includes CAH),Rehabilitation Hospital,Rehabilitation Hospital
ccn_facility_type,Short-Term Hospital,Critical Access Hospital,Short-Term Hospital,Rehabilitation Hospital,Rehabilitation Hospital
number_of_beds,114.0,25.0,46.0,100.0,70.0
total_bed_days_available,41610.0,9125.0,16790.0,36500.0,25550.0
occupancy_rate,0.472026,0.131068,0.159678,0.887068,0.663836
total_discharges__v___xviii___xix___unknown_,5283.0,155.0,892.0,2390.0,1370.0
total_days__v___xviii___xix___unknown_,19641.0,1196.0,2681.0,32378.0,16961.0
fte___employees_on_payroll,598.72,70.56,72.65,297.77,154.6
net_patient_revenue,63311578.0,8661723.0,13149507.0,39554420.0,20242022.0
total_income,-2691671.0,-837408.0,132630.0,11784376.0,4565066.0
net_income,-2691671.0,-837408.0,132630.0,11762647.0,4565066.0
total_costs,57980457.0,8826889.0,12664848.0,27772742.0,16520185.0
total_other_expenses,148432.0,148432.0,148432.0,21729.0,148432.0
total_assets,109224801.0,23319725.0,3634507.0,83044000.0,49107070.0
total_liabilities,13963740.0,18190741.0,1309043.0,6112321.0,1975069.0
total_current_assets,15310555.0,4766124.0,2895733.0,77489587.0,42597787.0
total_current_liabilities,1006274.0,842228.0,1377400.0,3056616.0,1975069.0
cash_on_hand_and_in_banks,6878054.0,933246.0,850541.0,73289485.0,40782630.0
accounts_receivable,6379506.0,2832699.0,4915619.0,4851517.0,1969952.0
accounts_payable,4100999.0,61242.0,1197880.0,524898.0,973226.0
profit_margin_calc,-0.042515,-0.096679,0.010086,0.297379,0.225524
cost_to_charge_ratio,0.282971,1.061421,0.641784,0.452421,0.663245
charity_care_ratio,0.022639,0.023203,0.016959,0.016959,0.016959
cost_of_charity_care,1312622.0,204811.0,1281423.5,1281423.5,1281423.5
total_unreimbursed_and_uncompensated_care,1439490.0,827330.0,1911488.0,-8796.0,-14956.0
hospital_name,Marshall Medical Center - South,Beartooth Billings Clinic,Lake Martin Community Hospital,Healthsouth Lakeshore Hospital,Healthsouth Rehabilitation Hospital
city,Boaz,Red Lodge,Dadeville,Birmingham,Largo
county,Marshall,Carbon,Tallapoosa,Jefferson,Pinellas
zip_code,35957,59806,36853,35209,33770
medicare_cbsa_number,13820.0,99927.0,99919.0,13820.0,45300.0
type_of_control,"Government, County","Voluntary Non-Profit, Other","Proprietary, Partnership","Proprietary, Corporation","Proprietary, Corporation"
state_full_name,Alabama,Montana,Alabama,Alabama,Florida
expense_ratio,0.915795,1.019068,0.963142,0.70214,0.816133
current_ratio,15.215095,5.658947,2.102318,25.35143,21.567746
debt_to_asset_ratio,0.127844,0.780058,0.360171,0.073603,0.04022
revenue_per_bed,555364.719298,346468.92,285858.847826,395544.2,289171.742857
staff_to_bed_ratio,5.25193,2.8224,1.579348,2.9777,2.208571
discharges_per_bed,46.342105,6.2,19.391304,23.9,19.571429
avg_length_of_stay,3.717774,7.716129,3.005605,13.54728,12.380292
uncompensated_care_percent,2.482716,9.372838,15.092862,-0.031671,-0.090532
charity_care_percent,2.263904,2.320308,10.117954,4.613961,7.756714
rucc_code,4.0,3.0,6.0,1.0,1.0
rural_urban,Rural,Urban,Rural,Urban,Urban

In [14]:
# Saving the updated hospital dataset
hospital.to_csv(r"C:\Users\manju\OneDrive\Desktop\Documents\Data Analytics\DA Semester 4\Capstone 2\ML Modelling\hospital_kpi_ready_with_rucc.csv", index=False)

In [15]:
# Display final dataset sample
cms_rucc_data = pd.read_csv(r"C:\Users\manju\OneDrive\Desktop\Documents\Data Analytics\DA Semester 4\Capstone 2\ML Modelling\hospital_kpi_ready_with_rucc.csv")
cms_rucc_data.head().T

,0,1,2,3,4
year,2011,2011,2011,2011,2011
state_code,AL,MT,AL,AL,FL
provider_type,General Short-Term (includes CAH),General Short-Term (includes CAH),General Short-Term (includes CAH),Rehabilitation Hospital,Rehabilitation Hospital
ccn_facility_type,Short-Term Hospital,Critical Access Hospital,Short-Term Hospital,Rehabilitation Hospital,Rehabilitation Hospital
number_of_beds,114.0,25.0,46.0,100.0,70.0
total_bed_days_available,41610.0,9125.0,16790.0,36500.0,25550.0
occupancy_rate,0.472026,0.131068,0.159678,0.887068,0.663836
total_discharges__v___xviii___xix___unknown_,5283.0,155.0,892.0,2390.0,1370.0
total_days__v___xviii___xix___unknown_,19641.0,1196.0,2681.0,32378.0,16961.0
fte___employees_on_payroll,598.72,70.56,72.65,297.77,154.6
net_patient_revenue,63311578.0,8661723.0,13149507.0,39554420.0,20242022.0
total_income,-2691671.0,-837408.0,132630.0,11784376.0,4565066.0
net_income,-2691671.0,-837408.0,132630.0,11762647.0,4565066.0
total_costs,57980457.0,8826889.0,12664848.0,27772742.0,16520185.0
total_other_expenses,148432.0,148432.0,148432.0,21729.0,148432.0
total_assets,109224801.0,23319725.0,3634507.0,83044000.0,49107070.0
total_liabilities,13963740.0,18190741.0,1309043.0,6112321.0,1975069.0
total_current_assets,15310555.0,4766124.0,2895733.0,77489587.0,42597787.0
total_current_liabilities,1006274.0,842228.0,1377400.0,3056616.0,1975069.0
cash_on_hand_and_in_banks,6878054.0,933246.0,850541.0,73289485.0,40782630.0
accounts_receivable,6379506.0,2832699.0,4915619.0,4851517.0,1969952.0
accounts_payable,4100999.0,61242.0,1197880.0,524898.0,973226.0
profit_margin_calc,-0.042515,-0.096679,0.010086,0.297379,0.225524
cost_to_charge_ratio,0.282971,1.061421,0.641784,0.452421,0.663245
charity_care_ratio,0.022639,0.023203,0.016959,0.016959,0.016959
cost_of_charity_care,1312622.0,204811.0,1281423.5,1281423.5,1281423.5
total_unreimbursed_and_uncompensated_care,1439490.0,827330.0,1911488.0,-8796.0,-14956.0
hospital_name,Marshall Medical Center - South,Beartooth Billings Clinic,Lake Martin Community Hospital,Healthsouth Lakeshore Hospital,Healthsouth Rehabilitation Hospital
city,Boaz,Red Lodge,Dadeville,Birmingham,Largo
county,Marshall,Carbon,Tallapoosa,Jefferson,Pinellas
zip_code,35957,59806,36853,35209,33770
medicare_cbsa_number,13820.0,99927.0,99919.0,13820.0,45300.0
type_of_control,"Government, County","Voluntary Non-Profit, Other","Proprietary, Partnership","Proprietary, Corporation","Proprietary, Corporation"
state_full_name,Alabama,Montana,Alabama,Alabama,Florida
expense_ratio,0.915795,1.019068,0.963142,0.70214,0.816133
current_ratio,15.215095,5.658947,2.102318,25.35143,21.567746
debt_to_asset_ratio,0.127844,0.780058,0.360171,0.073603,0.04022
revenue_per_bed,555364.719298,346468.92,285858.847826,395544.2,289171.742857
staff_to_bed_ratio,5.25193,2.8224,1.579348,2.9777,2.208571
discharges_per_bed,46.342105,6.2,19.391304,23.9,19.571429
avg_length_of_stay,3.717774,7.716129,3.005605,13.54728,12.380292
uncompensated_care_percent,2.482716,9.372838,15.092862,-0.031671,-0.090532
charity_care_percent,2.263904,2.320308,10.117954,4.613961,7.756714
rucc_code,4.0,3.0,6.0,1.0,1.0
rural_urban,Rural,Urban,Rural,Urban,Urban

In [16]:
hospital["rucc_code"].value_counts().sort_index()
hospital["rural_urban"].value_counts()

rural_urban
Urban    45062
Rural    23022
Name: count, dtype: int64